ALTER TABLE user_info ADD COLUMN LIQUIDACION_ACTIVA_ID BIGINT;
ALTER TABLE user_info ADD CONSTRAINT fk_user_info_liquidacion FOREIGN KEY (LIQUIDACION_ACTIVA_ID) REFERENCES liquidaciones (id);

UPDATE user_info SET LIQUIDACION_ACTIVA_ID = 74202 WHERE id = 1;